services:
  nginx:
    build: ./BobPlanning.front
    container_name: nginx-server
    volumes:
      - ./BobPlanning.front/dockerization/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - node-app
      - db
    networks:
      - app-network

  node-app:
    build: ./BobPlanning.back
    container_name: node-application
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./BobPlanning.back:/usr/src/app
      - /home/bob/bobPlanning.db/db.conf:/BobPlanning.back/dist/database/config/db.conf

    networks:
      - app-network


  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bobPlanning
      MYSQL_USER: bob
      MYSQL_PASSWORD: thisIsBobPlanning!
    ports:
      - "3307:3306"
    volumes:
      - ../bobPlaning.db:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-database
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
