services:
  nginx:
    build: ./BobPlanning.front
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - node-app
      - db
    networks:
      - app-network

  node-app:
    build: ./BobPlanning.back
    container_name: node-application
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./BobPlanning.back/dist:/usr/src/app
    networks:
      - app-network


  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bobPlanning
      MYSQL_USER: bob
      MYSQL_PASSWORD: thisIsBobPlanning!
    ports:
      - "3306:3306"
    volumes:
      - ../bobPlaning.db:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
