# dans backend config/database/db.conf: remplacer localhost par opale-database

services:
#  nginx:
#    build: ./BobPlanning.front
#    container_name: opale-frontend
#    depends_on:
#      - node-app
#    networks:
#      - app-network
#    ports:
#      - "80:80"
#    volumes:
#      - ./BobPlanning.front/dockerization/nginx.conf:/etc/nginx/nginx.conf:z

  node-app:
    build:
      context: ./BobPlanning.back
      dockerfile: Dockerfile.dev
    container_name: opale-backend
    depends_on:
      - db

    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./BobPlanning.back:/usr/src/app:z
      - /usr/src/app/node_modules
    networks:
      - app-network
      - api-network
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


  db:
    image: postgres:15
    container_name: opale-postgres-database
    env_file: 
      - BobPlanning.database/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./BobPlanning.database/init-scripts:/docker-entrypoint-initdb.d:z
    networks:
      - app-network

  opale-new-frontend:
    build:
      context: ./Opale.Front
      dockerfile: Dockerfile.dev
    container_name: opale-new-frontend
    depends_on:
      - node-app
    volumes:
      - ./Opale.Front:/app:z
      - /app/node_modules
    networks:
      - app-network
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_RACINE_FETCHER_URL=http://localhost:3000
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:community
    container_name: opale-sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - app-network

  sonarqube-db:
    image: postgres:15
    container_name: opale-sonarqube-db
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube_postgres:/var/lib/postgresql/data
    networks:
      - app-network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: opale-sonar-scanner
    depends_on:
      - sonarqube
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN: ${SONAR_TOKEN}
    volumes:
      - .:/usr/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_postgres: