services:
  nginx:
    build: ./
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - node-app
      - db
    networks:
      - app-network

  node-app:
    build: ./
    container_name: node-application
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network