version: "3.9"

# dans backend config/database/db.conf: remplacer localhost par opale-database

services:
  nginx:
    build: ./BobPlanning.front
    container_name: opale-frontend
    depends_on:
      - node-app
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./BobPlanning.front/dockerization/nginx.conf:/etc/nginx/nginx.conf:z

  node-app:
    build: ./BobPlanning.back
    container_name: opale-backend
    depends_on:
      - db
    networks:
      - app-network
      - api-network
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    build: ./BobPlanning.database
    container_name: opale-database
    env_file: 
      - ./BobPlanning.database/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:z
    networks:
      - app-network

  python-api:
    build: ./BobPlanning.microService
    container_name: opale-python-api
    networks:
      - api-network
    ports:
      - "5000:5000"   # adapte au port réel de ton microservice

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge

volumes:
  mysql_data:
