sonar.projectKey=Opale
sonar.projectName=Opale
sonar.sources=.
sonar.host.url=http://localhost:9000

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/coverage/**

sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.js,**/*.spec.ts,**/*.spec.js
