spring.application.name=micro-planning

# Database Configuration (only enabled when PostgreSQL is available)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/${POSTGRES_DB}}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration (only enabled when database is available)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Logging
logging.level.com.opale.micro_planning=INFO
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
