name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        run: cd BobPlanning.back && npm ci
      - name: Run ESLint with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: ". --ext .ts,.js"

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd BobPlanning.back && npm ci
      - run: cd BobPlanning.back && npm test

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build backend Docker
        run: docker build -t myapp-back ./BobPlanning.back
      - name: Build frontend Docker
        run: docker build -t myapp-front ./BobPlanning.front
      - name: Build database Docker
        run: docker build -t myapp-db ./database

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with docker-compose
        run: docker-compose up -d --build
