name: Deploy to Server

on:
  workflow_dispatch: # Permet de déclencher ce workflow manuellement depuis l'interface GitHub
  push:
    branches:
      - deploy

jobs:

  deploy:
    runs-on: self-hosted
  strategy:
      matrix:
        runner: [bob, ubuntu-1]  # Remplace par tes labels de runners

    steps:
    - name: Check Node.js version
      run: node -v

    - name: Check npm version
      run: npm -v

    - name: Récupérer le code
      uses: actions/checkout@v3

    - name: Deploy on server
      run: |
          cd /home/bob/bobPlanning.app
          git pull origin deploy
          docker-compose down
          docker-compose build
          docker-compose up -d
